name: flutter_password_calculator
description: A highly customizable password calculator. It has features such as password strenght and rules validation.
version: 1.0.1
repository: https://github.com/kayson91/flutter_password_calculator
homepage: https://phoenix-codes.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  password_strength: ^0.2.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


scripts: kayson.yaml

flutter: